# [START django_app]
runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT clmits.wsgi
instance_class: F1
handlers:
  - url: /static/(.*)
    static_files: static/\1
    require_matching_file: false
    upload: static/.*

  - url: /.*
    script: auto
  - url: .*
    script: auto

  - url: /static
    static_dir: staticfiles
    
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

network: {}
# [END django_app]